const strings = {
  hello: 'Hello Jessie,',
  atTheMoment: 'at the moment you have',
  thirtytwo: '32,5 GB',
  of100: 'of 100 GB',
  files: 'FILES',
  folders: 'FOLDERS',
  nextBigThing: 'The next big thing',
  topSecret: 'Top Secret',
  freebieProject: 'Freebie project',
  londonMeetup: 'London Meetup',
  f12: '12 f - 2.1 gb',
  f7: '7 f - 523 mb',
  f3: '3 f - 192 mb',
  f453: '453 f - 1.7 gb',
  profile: 'Profile',
  jessie: 'Jessie Roberts',
  files1458: '1458 files - 25 folders',
  increaseSpace: 'Increase storage space',
  storageManagement: 'Storage management',
  devices: 'Devices',
  iphone_mac_ipad: 'iPhone, Macbook, iPad',
  cameraUploads: 'Camera uploads',
  useDataForFileTransfer: 'Use data for file transfer',
  more7: '+7',
  more2: '+2',
  more3: '+3',
  yourCloudStorage: 'Your cloud storage',
  safeAndSound: 'safe and sound',
};

export default strings;
